# Generated by Django 4.2.2 on 2023-09-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_item_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('list', 'text')},
        ),
    ]
